Problem: Compilation errors on Elixir 1.2.0-dev
Latest Elixir master introduces additional compilation warnings.
This patch fixes some of them:

---

lib/credo/check/design/duplicated_code.ex:122:
warning: you are piping into a function call without parentheses, which is ambiguous. Please wrap the function you are piping into in parentheses. For example:

    foo 1 |> bar 2 |> baz 3

Should be written as:

    foo(1) |> bar(2) |> baz(3)

---

lib/credo/check/readability/trailing_white_space.ex:20:
warning: an expression is always required on the right side of ->. Please provide a value after ->

---

lib/credo/cli/output/issues_short_list.ex:15:
warning: an expression is always required on the right side of ->. Please provide a value after ->

---

lib/credo/config.ex:87:
warning: default arguments in from_exs/3 are never used